version: '3.8'

services:
  # See also https://habr.com/ru/post/578744/
  postgres:
    image: postgres:15.1

    # With the "env_file" option you can specify a file with variables to be injected
    # into the environment in the container.
    env_file:
      - ./keycloak-postgres.env

    container_name: keycloak-db
    restart: unless-stopped
    ports:
      - '55432:5432'
    volumes:
      - /docker-compose-keycloak/postgresql_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    healthcheck:
      # We must use the "CMD-SHELL" take advantage of variable substitution or features like "|" and ">"
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_HEALTH_USER}" ]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 3

  keycloak:
#    hostname: mydebian.local
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.2
    restart: unless-stopped
    env_file:
      - ./keycloak-postgres.env
    environment:
      KC_FEATURES:
        authorization
        token-exchange
        docker
        impersonation
        scripts
        upload-scripts
        web-authn
        client-policies
        dynamic-scopes
    entrypoint: /opt/keycloak/bin/kc.sh start
    volumes:
      - /docker-compose-keycloak/keycloak_data/server.crt.pem:/opt/keycloak/conf/server.crt.pem
      - /docker-compose-keycloak/keycloak_data/server.key.pem:/opt/keycloak/conf/server.key.pem
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - keycloak-network
    healthcheck:
      # "--insecure" to disable verification a self-signed certificate
      # "--fail" to fail fast with no output at all on server errors.
      # "--silent" to silent or quiet mode. Do not show progress meter or error messages.
      test: [ "CMD", "curl", "--insecure", "--fail", "--silent", "https://localhost:8443/health/ready" ]
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - postgres

networks:
  keycloak-network:
    driver: bridge